Fix test execution errors
javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: error performing isolated
java.sql.SQLSyntaxErrorException: Table 'oscar_test.hibernate_sequence' doesn't exist