issue: Print preview option for consult requests do not seem to work though other actions such as “update” or “submit' works fine. Nothing seems to happen, the screen remains on the consult request page. I have waited up-to 10 min without any print preview showing up. See below for testing steps that can be recreated.
tl;dr: I think the issue is simply a slow sql query that uses a subquery, and that can be easily replaced with a join.

More details:

a) by using Java Melody, I observed that when I attempted to do a print preview, the thread was stuck on java.net.SocketInputStream.socketRead0(Native Method) It would run for 40+ minutes, and then eventually get killed

b) only once the thread got killed, did errors show up in the docker logs:

javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute query
at org.hibernate.ejb.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:614) ~[hibernate-entitymanager-3.4.0.GA.jar:3.4.0.GA]
at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:76) ~[hibernate-entitymanager-3.4.0.GA.jar:3.4.0.GA]
at org.oscarehr.common.dao.EFormDataDao.findByDemographicIdCurrentAttachedToConsult(EFormDataDao.java:121) ~[classes/:0.0.0-SNAPSHOT]
at [snip]
at oscar.eform.EFormUtil.listPatientEformsCurrentAttachedToConsult(EFormUtil.java:251) ~[classes/:0.0.0-SNAPSHOT]
at oscar.oscarEncounter.oscarConsultationRequest.pageUtil.EctConsultationFormRequestPrintAction2.execute(EctConsultationFormRequestPrintAction2.java:207) ~[classes/:0.0.0-SNAPSHOT]
at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:419) ~[struts-1.2.7.jar:1.2.7]

c) when I investigated the relevant function call (findByDemographicIdCurrentAttachedToConsult) this is the query:

String sql = "SELECT * FROM eform_data e where e.patient_independent = false " + "AND e.fdid IN (SELECT cd.document_no FROM consultdocs cd WHERE cd.requestId = '" + consultationId + "' AND cd.docType = 'E' AND cd.deleted IS NULL) " + "ORDER BY e.form_date DESC, e.form_time DESC";

e) When I ran this query on the QA DB via a GUI editor using an applicable consultationID (E.g. 91460), the query that took 37 minutes to execute.

SELECT * FROM eform_data e where e.patient_independent = false AND e.fdid IN (SELECT cd.document_no FROM consultdocs cd WHERE cd.requestId = '91460' AND cd.docType = 'E' AND cd.deleted IS NULL) ORDER BY e.form_date DESC, e.form_time DESC;

f) I THINK it’s possible to rewrite this query with a join but have them logically equivalent:

SELECT e.* FROM eform_data e JOIN consultdocs cd ON e.fdid = cd.document_no WHERE e.patient_independent = false AND cd.requestId = '91460' AND cd.docType = 'E' AND cd.deleted IS NULL ORDER BY e.form_date DESC, e.form_time DESC;

g) this alternative query executed instantly on QA. When this change was made in development, the print preview (which had already showed up before, seemed to show up faster now)

h) my hypothesis is that the print preview is not working on QA only because this query, while valid, is taking too long to execute, thus giving the perception of things hanging.

i) I think the solution is to simply use the join version of the query, instead of the subquery version.

Recommendation for reviewer. If you agree a join is logically equivalent and likely faster, the following function in the same file should likely be tweaked as well. It has a very similar subquery that I think could be replaced with a join for efficiency reasons. I didn’t know a way to test this function though, so I didn’t submit a pull request.

public List<EFormData> findByDemographicIdCurrentAttachedToEForm(String fdid) {
  if(StringUtils.isEmpty(fdid)) {
     return new ArrayList<EFormData>();
  }
  String sql = "SELECT * FROM eform_data e where e.patient_independent = false " + "AND e.fdid IN (SELECT cd.document_no FROM EFormDocs cd WHERE cd.fdid = '" + fdid + "' AND cd.docType = 'E' AND cd.deleted IS NULL) " + "ORDER BY e.form_date DESC, e.form_time DESC";
  Query query = entityManager.createNativeQuery(sql, modelClass);
  return query.getResultList();
}